# simple3 - flext tutorial example
# Copyright (c) 2001,2002 Thomas Grill (xovo@gmx.net)
#
# Makefile for BorlandC++ 
#
# usage: make -f makefile.bcc
#
# ---------------------------------------------

NAME=simple3
SETUPFUNCTION=simple3_setup

!include ..\makefile-inc.bcc
