# signal2 - flext tutorial example
# Copyright (c) 2001,2002 Thomas Grill (xovo@gmx.net)
#
# Makefile for BorlandC++ 
#
# usage: make -f makefile.bcc
#
# ---------------------------------------------

NAME=signal2~
SETUPFUNCTION=signal2_tilde_setup

!include ..\makefile-inc.bcc

